package com.LsmFiServices.Utility;

public class Queries {

    public static final String PROVIDER_URL_QUERY = "SELECT CONFIGURATION_VALUE FROM ICOS_CONFIGURATION WHERE CONFIGURATION_PARAM =  ?";
    public static final String SAVE_SERVICE_EXCEPTION = "INSERT INTO LSM_FI_EXCEPTIONS (PINSTID, REQUESTTYPE, RAISED_EXCEPTION, DATETIME) VALUES (?,?,?,SYSDATE)";
    public static final String GET_FI_COUNT_EXECUTION_TABLE = "SELECT  COUNT(PINSTID) AS COUNTFROMEXECUTIONTABLE FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID =  ?";
    public static final String FLUSH_DATA = "DELETE FROM  LSM_FI_EXECUTION_DETAILS  WHERE PINSTID =?";
    public static final String UPDATE_COUNT_IN_EXT = "UPDATE  LIMIT_SETUP_EXT SET FI_EXECUTION_COUNT =?  WHERE PINSTID =  ?";
    public static final String GET_FI_COUNT_FROM_EXT = "SELECT  FI_EXECUTION_COUNT FROM LIMIT_SETUP_EXT WHERE PINSTID =  ?";
    public static final String SAVE_SERVICE_EXECUTION_DETAILS = "INSERT INTO LSM_FI_EXECUTION_DETAILS (PINSTID,SERVICE_NAME,REQUEST_TYPE,FACILITY,ACCOUNT_NUMBER,REQUEST,RESPONSE,STATUS,MESSAGE,DATETIME,HOST_NAME) VALUES (?,?,?,?,?,?,?,?,?,SYSDATE,?)";
    public static final String GET_SERVICE_INPUT_DETAILS = "SELECT QUESTION, QUESTION_ID,ANSWER AS ACCOUNT_NUMBER FROM LSM_LIMIT_ANSWERS WHERE PINSTID = ? AND FACILITY_NAME = ? AND QUESTION_ID LIKE '149%'";
    public static final String GET_MEMO_TYPE = "SELECT MEMO_TYPE  FROM LIMIT_SETUP_EXT WHERE PINSTID = ?";
    public static final String GET_DISHUBID = "SELECT DISHUBID FROM LIMIT_SETUP_EXT WHERE PINSTID= ?";
    public static final String GET_INCOMPLETE_LSM_FLAG = "SELECT STATUS FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID = ? AND SERVICE_NAME = ?";
//    public static final String GET_STATUS_FROM_EXECUTION_TABLE = "SELECT STATUS FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID = ? AND (REQUEST_TYPE != 'CRM_SERVICE' OR REQUEST_TYPE  IS NULL) AND STATUS NOT IN('FAILURE','FAILED','F','Request Sent...!') AND STATUS IS NOT NULL";
    public static final String GET_STATUS_FROM_EXECUTION_TABLE = "SELECT STATUS FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID = ? AND (REQUEST_TYPE != 'CRM_SERVICE' OR REQUEST_TYPE IS NULL)";
    public static final String UPDATE_STATUS_IN_EXT = "UPDATE LIMIT_SETUP_EXT SET FI_SERVICE_STATUS = ? WHERE PINSTID = ? ";
    public static final String SAVE_APP_START_TIME = "INSERT INTO LSM_FI_RUNTIME_DETAILS (HOSTNAME, APP_START_TIMESTAMP) VALUES (?,?)";
    public static final String UPDATE_APP_SHUTDOWN_TIME = "UPDATE LSM_FI_RUNTIME_DETAILS SET APP_SHUTDOWN_TIMESTAMP = ? WHERE APP_START_TIMESTAMP =? AND HOSTNAME = ?";
    public static final String GET_FACILITY_LIMIT_AMOUNT = "SELECT ANSWER AS FAC_LIMIT_AMOUNT FROM LSM_LIMIT_ANSWERS WHERE PINSTID =?  AND FACILITY_NAME =? AND QUESTION_ID = ?";
    public static final String GET_FACILITY_LIMIT_AMOUNT_CROSS_CALL = "SELECT ANSWER AS FAC_LIMIT_AMOUNT FROM LSM_CROSS_CALL_ANSWERS WHERE PINSTID =?  AND FACILITY_NAME =? AND QUESTION_ID = ?";
    public static final String GET_PSL_OTHERS_DETAILS = "SELECT (SELECT (CASE WHEN UPPER(SECTOR_CODE) = 'PRIORITY' THEN '1' ELSE '2' END )  FROM PSL_DETAILS_OTHERS WHERE PINSTID =? AND FACILITY_NAME = ?) AS SECTOR_CODE, SUB_SECTOR_CODE, MODE_OF_ADVANCE,FACILITY_NAME FROM PSL_DETAILS_OTHERS WHERE PINSTID = ? AND FACILITY_NAME = ?";
    public static final String GET_SUB_TYPE_SECURITY_SVT = "SELECT DISTINCT ANSWER AS SUB_TYPE_SECURITY_SVT,SECURITY_PROVIDER_ID,SECURITY_PROVIDER_NAME , QUESTION_ID FROM  LSM_SECURITY_ANSWERS  WHERE PINSTID = ?  AND  SECURITY_PROVIDER_NAME =? AND QUESTION =? ORDER BY SECURITY_PROVIDER_NAME";
    public static final String GET_SECURITYWISE_PRODUCTS = "SELECT SECURITY_PROVIDER_NAME,QUESTION_ID, QUESTION,ANSWER AS PRODUCT FROM LSM_SECURITY_ANSWERS WHERE PINSTID =? AND SECURITY_PROVIDER_NAME=? AND QUESTION = ? ORDER BY QUESTION_ID";
    public static final String GET_SVT_OTHER_DETAILS = "SELECT  A.SECURITY_DETAILS, A.TYPE_SEC_CREATION,A.SEELING_LIMIT,B.REF_DESC, B.REF_CODE,  C.ICORE_CODE AS DERIVED_VALUE FROM CAL_SECURITY_DETAILS_SECURED A  JOIN LSM_MS_NATURE_OF_CHARGE B ON UPPER(B.REF_DESC) = UPPER(A.TYPE_SEC_CREATION)  JOIN LSM_MS_DERIVED_VALUE C  ON UPPER(C.SCREEN_LEVEL_DROPDOWN) = UPPER(A.DERIVED_VALUE) WHERE PINSTID =(SELECT DISHUBID FROM LIMIT_SETUP_EXT WHERE PINSTID=?)";
    public static final String FETCH_LSM_NUMBER = "SELECT ANSWER AS LSM_NO FROM LSM_MS_ANSWERS  WHERE PINSTID =? AND QUESTION_ID ='2'";
    public static final String GET_COLLATERAL_AMOUNT_SVT = "SELECT DISTINCT QUESTION, ANSWER, SECURITY_PROVIDER_NAME, SECURITY_PROVIDER_ID FROM LSM_SECURITY_ANSWERS WHERE PINSTID = ? AND SECURITY_PROVIDER_NAME= ? AND QUESTION=?";
    public static final String GET_COLLATERAL_CODE_SVT = "SELECT DISTINCT ICORE_CODE AS COLLATERAL_CODE FROM UNICORE_MS_SUBTYPE_SVT WHERE SUB_TYPE_SECURITY_SVT =?";
    public static final String FETCH_REASON_FOR_RENEWAL = "SELECT ANSWER AS REASON_FOR_RENEWAL FROM LSM_LIMIT_ANSWERS WHERE PINSTID = ? AND QUESTION_ID=?";
    public static final String FETCH_LEI_URCC_NUMS = "SELECT * FROM ( SELECT HOME.QUESTION_ID   HOME_QUESTION, HOME.ANSWER HOME_ANSWER FROM LSM_MS_ANSWERS HOME WHERE HOME.PINSTID = ?  AND HOME.QUESTION_ID IN ('28','18','19')  ) PIVOT (MAX ( HOME_ANSWER ) FOR HOME_QUESTION IN ( 28 AS URCC,18 AS LEI, 19 AS LEI_EXPIRY_DATE))";
    public static final String FETCH_CUSTID = "SELECT ANSWER AS CUSTID FROM LSM_LIMIT_ANSWERS WHERE PINSTID =?  AND QUESTION_ID=?";
    public static final String FETCH_CROSS_CALL_DETAILS = "SELECT * FROM (SELECT CROSS_CALL.QUESTION_ID CROSS_CALL_QUESTION, CROSS_CALL.ANSWER CROSS_CALL_ANSWER, CROSS_CALL.FACILITY_NAME FACILITY_NAME FROM LSM_CROSS_CALL_ANSWERS CROSS_CALL WHERE CROSS_CALL.PINSTID = ? AND CROSS_CALL.QUESTION_ID IN ('146','127','171','132','133','155','156','128','129','149','49','163','164','137', '134', '130', '131','122', '123', '150','125','126','141','165','211','226')) PIVOT (MAX ( CROSS_CALL_ANSWER ) FOR CROSS_CALL_QUESTION IN ( 146 AS CURRENCY_ONE,127 AS AMOUNT_LIMIT,171 AS CURRENCY_TWO,132 AS SECURITY_PROVIDER,133 AS LIMIT_EXP_DATE,155 AS LIMIT_PREFIX,129 AS SANCTION_DATE,156 AS LIMIT_SUFFIX,128 AS SANCTION_AMOUNT,146 AS CURRENCY_THREE, 149 AS ACCOUNT_NO, 49 AS DISTRICT, 163 AS LIEN_APPLICABILITY, 164 AS LIEN_AMOUNT, 137 AS DOCUMENT_AMOUNT,134 AS FACILITY_EXP_DATE , 130 AS SANCTION_VAL_DATE, 131 AS SANCTION_FORUM , 122 AS BUSINESS_MODEL , 123 AS SPPI, 150 AS FA_EXECUTION_DATE ,125 AS SEQUENCE_NO, 126 AS CROSS_CALL_MAIN_LIMIT , 141 AS IS_REVOCABLE, 165 AS LIEN_IN_FAVOUR_OF,211 AS CROSS_CALL_EXISTING_LIMIT, 226 AS TYPE_OF_SERVICE)) ORDER BY SEQUENCE_NO";
    public static final String GET_CROSS_CALL_MAIN_LIMIT_DETAILS = "SELECT * FROM (SELECT LIMIT.QUESTION_ID AS LIMIT_QUESTION, LIMIT.ANSWER AS LIMIT_ANSWER,LIMIT.FACILITY_NAME  FROM LSM_LIMIT_ANSWERS LIMIT WHERE LIMIT.PINSTID = ?  and LIMIT.FACILITY_NAME = ? AND LIMIT.QUESTION_ID IN ('155','156'))  PIVOT ( MAX (LIMIT_ANSWER)  FOR LIMIT_QUESTION  IN ('155' AS MAIN_LIMIT_PREFIX_FOR_CROSS_CALL ,'156' AS MAIN_LIMIT_SUFFIX_FOR_CROSS_CALL)) ";
    public static final String FETCH_CROSS_CALL_INDIVIDUAL_DETAILS = "SELECT * FROM (SELECT CROSS_CALL.QUESTION_ID CROSS_CALL_QUESTION, CROSS_CALL.ANSWER CROSS_CALL_ANSWER, CROSS_CALL.FACILITY_NAME FACILITY_NAME FROM LSM_CROSS_CALL_ANSWERS CROSS_CALL WHERE CROSS_CALL.PINSTID = ? AND FACILITY_NAME = ? AND CROSS_CALL.QUESTION_ID IN ('146','127','171','132','133','155','156','128','129','149','49','163','164','137', '134', '130', '131','122', '123', '150','125','126','141','165','211')) PIVOT (MAX ( CROSS_CALL_ANSWER ) FOR CROSS_CALL_QUESTION IN ( 146 AS CURRENCY_ONE,127 AS AMOUNT_LIMIT,171 AS CURRENCY_TWO,132 AS SECURITY_PROVIDER,133 AS LIMIT_EXP_DATE,155 AS LIMIT_PREFIX,129 AS SANCTION_DATE,156 AS LIMIT_SUFFIX,128 AS SANCTION_AMOUNT,146 AS CURRENCY_THREE, 149 AS ACCOUNT_NO, 49 AS DISTRICT, 163 AS LIEN_APPLICABILITY, 164 AS LIEN_AMOUNT, 137 AS DOCUMENT_AMOUNT,134 AS FACILITY_EXP_DATE , 130 AS SANCTION_VAL_DATE, 131 AS SANCTION_FORUM , 122 AS BUSINESS_MODEL , 123 AS SPPI, 150 AS FA_EXECUTION_DATE ,125 AS SEQUENCE_NO, 126 AS CROSS_CALL_MAIN_LIMIT , 141 AS IS_REVOCABLE, 165 AS LIEN_IN_FAVOUR_OF, 211 AS CROSS_CALL_EXISTING_LIMIT)) ORDER BY SEQUENCE_NO";
    public static final String  GET_EXISTING_LIMIT_FLAG_FOR_CROSS_CALL = "SELECT ANSWER AS EXISTING_LIMIT_AS_PER_SANCTION_FOR_CROSS_CALL FROM LSM_CROSS_CALL_ANSWERS WHERE PINSTID = ? AND FACILITY_NAME =?  AND QUESTION_ID =? ";
    public static final String  GET_EXISTING_LIMIT_FLAG = "SELECT ANSWER AS EXISTING_LIMIT_AS_PER_SANCTION FROM LSM_LIMIT_ANSWERS WHERE PINSTID = ? AND FACILITY_NAME =?  AND QUESTION_ID =? ";
//    public static final String GET_CHILD_SERVICE_FLAG= "SELECT CASE COUNT(STATUS) WHEN 0 THEN 'TRUE' ELSE 'FALSE' END AS STATUS FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID =? AND SERVICE_NAME LIKE 'CHILD LIMIT NODE%' AND UPPER(STATUS) != 'SUCCESS'";
    public static final String GET_CHILD_SERVICE_FLAG= "SELECT CASE COUNT(STATUS) WHEN 0 THEN 'TRUE' ELSE 'FALSE' END AS STATUS FROM LSM_FI_EXECUTION_DETAILS WHERE PINSTID =? AND (SERVICE_NAME LIKE 'CHILD LIMIT NODE%' AND REQUEST_TYPE NOT LIKE 'CHILD LIMIT NODE%%CROSS CALL') AND UPPER(STATUS) != 'SUCCESS'";

    
    public static final String  GET_FLAG_FOR_LEI_URCC = "SELECT CUSTID_ACCOUNT_SPECIFIC FROM  LSM_RM_SIGNED_API_INFO WHERE PINSTID IN (?,(SELECT DISHUBID FROM LIMIT_SETUP_EXT WHERE PINSTID = ?)) AND UPPER(FLAG) = 'SUCCESS' AND FACILIY !='Penal Account' ";

    // Drawing power
    public static final String GET_DRAWING_POWER_RESPONSE = "SELECT RESPONSE_MESSSAGE FROM LSM_SERVICE_REQ_RES  WHERE PINSTID = ? AND STATUS =? AND REQUESTTYPE =? ORDER BY DATETIME DESC FETCH FIRST ROW ONLY ";
    
    public static final String INSERT_FEE_REQ_RES= "INSERT INTO LSM_SERVICE_REQ_RES (PINSTID,REQUEST_MESSAGE,RESPONSE_MESSSAGE,REQUESTTYPE,STATUS,DATETIME,RECORDID,MESSAGE,HOST_NAME) VALUES (?,?,?,?,?,SYSDATE,AUTO_INCREMENT_RECORDID.nextval,?,?)";
    public static final String INSERT_LSM_SCHEDULER_PINSTIDS= "INSERT INTO LSM_SCHEDULER_PINSTIDS (PINSTID, FI_EXECUTION_DATE_TIME) VALUES (?, SYSDATE)";
    public static final String DELETE_LSM_SCHEDULER_PINSTIDS= "DELETE FROM LSM_SCHEDULER_PINSTIDS WHERE PINSTID = ?";
    public static final String GET_TYPE_OF_SERVICE = "SELECT ANSWER AS TYPEOFSERVICE FROM LSM_LIMIT_ANSWERS WHERE PINSTID =?  AND FACILITY_NAME =? AND QUESTION_ID = ?";
    public static final String GET_TYPE_OF_SERVICE_CROSS_CALL = "SELECT ANSWER AS TYPEOFSERVICE FROM LSM_CROSS_CALL_ANSWERS WHERE PINSTID =?  AND FACILITY_NAME =? AND QUESTION_ID = ?";

}
